version: 0.2

env:
  secrets-manager:
    GITHUB_TOKEN: MyGitHubToken:github_token

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install awscli jq
      - echo "Retrieving GitHub token from Secrets Manager..."
      - export GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id MyGitHubToken --query SecretString --output text | jq -r '.github_token')
      - git config --global credential.helper 'store --file ~/.my-credentials'
      - echo "https://$GITHUB_TOKEN:@github.com" > ~/.my-credentials
  build:
    commands:
      - echo "Building and deploying the application..."
      - aws cloudformation update-stack --stack-name MyCloudAppStack --template-body file://YAML/template.yaml --capabilities CAPABILITY_IAM
artifacts:
  files:
    - '**/*'
