version: 0.2

env:
  secrets-manager:
    GITHUB_TOKEN: MyGithubToken:github_token

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install awscli jq
      - echo "Retrieving GitHub token from Secrets Manager..."
      - export GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id MyGithubToken --query SecretString --output text | jq -r '.github_token')
      - git config --global credential.helper 'store --file ~/.my-credentials'
      - echo "https://$GITHUB_TOKEN:@github.com" > ~/.my-credentials
  build:
    commands:
      - echo "Building and deploying the application..."
      - |
        STACK_NAME=${STACK_NAME:-MyCloudAppStack}
        TEMPLATE_FILE=YAML/template.yaml
        if ! aws cloudformation describe-stacks --stack-name $STACK_NAME; then
          echo "Stack does not exist, creating..."
          aws cloudformation create-stack --stack-name $STACK_NAME --template-body file://$TEMPLATE_FILE --capabilities CAPABILITY_IAM
          aws cloudformation wait stack-create-complete --stack-name $STACK_NAME
        else
          echo "Stack exists, updating..."
          aws cloudformation update-stack --stack-name $STACK_NAME --template-body file://$TEMPLATE_FILE --capabilities CAPABILITY_IAM
          aws cloudformation wait stack-update-complete --stack-name $STACK_NAME
        fi
artifacts:
  files:
    - '**/*'
